export const types = {
    uiOpenModal: '[UI] Open Modal',
    uiCloseModal: '[UI] Close Modal',
    calendarStartNewEvent: '[CALENDAR] Start Add New',
    calendarAddNewEvent: '[CALENDAR] Add New Event',
    calendarSetActiveEvent: '[CALENDAR] Set Active Event',
    calendarCleanActiveEvent: '[CALENDAR] Clean Event',
    calendarUpdateEvent: '[CALENDAR] Update Event',
    calendarUpdatedEvent: '[CALENDAR] Updated Event',
    calendarDeleteEvent: '[CALENDAR] Delete Event',
    calendarEventsLoaded: '[CALENDAR] Event Loaded',
    calendarLogout: '[CALENDAR] Clean Calendar State',
    authCheckingFinish: '[AUTH] Finish Checking Login State',
    authStartLogin: '[AUTH] Start Login',
    authLogin: '[AUTH] Login',
    authStartRegister: '[AUTH] Start Register',
    authStartTokenRenew: '[AUTH] Start Token Renew',
    authLogout: '[AUTH] Logout',
};
